### ISSUE TITLE
Could not pass event PlayerJoinEvent to TARDISChunkGenerator v4.11.0

### ISSUE THREAD

**Issue by roracle** [eccentricdevotion/TARDISChunkGenerator#7]
Console error.  Not sure what to do with this.
```
[14:20:10] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to TARDISChunkGenerator v4.11.0
java.lang.IllegalArgumentException: Duplicate handler name: roracle
	at io.netty.channel.DefaultChannelPipeline.checkDuplicateName(DefaultChannelPipeline.java:1055) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.DefaultChannelPipeline.filterName(DefaultChannelPipeline.java:284) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:247) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:237) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at me.eccentric_nz.tardischunkgenerator.helpers.TARDISPacketListener.injectPlayer(TARDISPacketListener.java:100) ~[TARDISChunkGenerator.jar:?]
	at me.eccentric_nz.tardischunkgenerator.disguise.TARDISDisguiseListener.onPlayerJoin(TARDISDisguiseListener.java:65) ~[TARDISChunkGenerator.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor24.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:git-Paper-86]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:366) ~[paper-1.19.1.jar:git-Paper-86]
	at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:308) ~[paper-1.19.1.jar:git-Paper-86]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:354) ~[?:?]
	at net.minecraft.network.Connection.tick(Connection.java:579) ~[?:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:233) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1582) ~[paper-1.19.1.jar:git-Paper-86]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.1.jar:git-Paper-86]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1415) ~[paper-1.19.1.jar:git-Paper-86]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[paper-1.19.1.jar:git-Paper-86]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.1.jar:git-Paper-86]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by eccentricdevotion** [comment]
Build 171 when it's done...
